Repository kujo205/db_labs, pull requests merged in 2023-09, with the labels that each got.

#1 project confuguration
  .gitignore
  docs/.vuepress/config.js
  docs/README.md
  package-lock.json
  package.json
  publish.sh
Labels: config

#14 edited all members' data in title page(#13)
  docs/README.md
Labels: feature

#20 lab1/Artem_Nikolaevi4 (#15)
  docs/requirements/state-of-the-art.md
Labels: lab1

#21 lab1/KobbAsa (#17)
  docs/requirements/state-of-the-art.md
Labels: lab1

#22 Lab1/igaryakqwe "(#16) Підходи та способи вирішення завдання"
  docs/requirements/state-of-the-art.md
Labels: lab1

#26 Lab1/igaryakqwe "(#16) Підходи та способи вирішення завдання"
  docs/requirements/state-of-the-art.md
Labels: lab1
