Repository kujo205/db_labs, pull requests merged in 2023-10, with the labels that each got.

#33 Added improved changes
  docs/requirements/logo.svg
  docs/requirements/stakeholders-needs.md
Labels: lab2

#40 lab4/KobbAsa (#39)
  docs/design/README.md
  docs/requirements/stakeholders-needs.md
Labels: lab4

#46 lab 4: Added relational scheme
  docs/design/README.md
Labels: lab4

#48 lab 5: Added SQL-script (#47)
  docs/software/README.md
Labels: lab5
